version: '3'
services: 
  satanbot:
    container_name: 'satan-bot'
    environment: 
      BOT_TOKEN:
    build: .
    restart: 'always'
    links:
      - mongo
      - redis
  mongo:
    container_name: 'satan-mongo'
    image: mongo
    restart: 'always'
    ports:
      - 27017:27017
  redis:
    container_name: 'satan-redis'
    image: redis
    restart: 'always'
    ports:
      - 6379:6379
    command: redis-server